//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jcEntityFramework.DataLayer.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class XMS_ColaEntities : DbContext
    {
        public XMS_ColaEntities()
            : base("name=XMS_ColaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int JCEFExecuteTestSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("JCEFExecuteTestSP");
        }
    
        public virtual ObjectResult<JCEFSelectTestSP_Result> JCEFSelectTestSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<JCEFSelectTestSP_Result>("JCEFSelectTestSP");
        }
    }
}
